use crate::{Agent, AgentCapability, AgentContext, CapabilityParameter};
use async_trait::async_trait;
use seehtml_core::*;

pub struct ExportAgent { state: AgentState }

impl ExportAgent {
    pub fn new() -> Self { Self { state: AgentState::Idle } }

    #[allow(dead_code)]
    async fn do_export(doc: &Document, opts: &ExportOptions) -> Result<String> {
        let theme = opts.theme.clone().unwrap_or_default();
        let output_path = opts.output_path.clone().unwrap_or_else(|| std::path::PathBuf::from(format!("{}.pptx", doc.title)));
        let path_str = output_path.to_string_lossy().to_string();
        let pptx = seehtml_export::build_pptx(doc, &theme)?;
        tokio::fs::write(&output_path, pptx).await?;
        Ok(path_str)
    }

    async fn export_markdown(doc: &Document, opts: &ExportOptions) -> Result<String> {
        let mut md = format!("# {}

", doc.title);
        md.push_str("> Generated by SeeHTML

");
        for section in &doc.sections {
            let prefix = "#".repeat(section.level as usize + 1);
            if let Some(heading) = &section.heading { md.push_str(&format!("{} {}

", prefix, heading)); }
            md.push_str(&section.content); md.push_str("

");
        }
        let p = opts.output_path.clone().unwrap_or_else(|| std::path::PathBuf::from(format!("{}.md", doc.title)));
        tokio::fs::write(&p, &md).await?;
        Ok(p.to_string_lossy().to_string())
    }
}

#[async_trait]
impl Agent for ExportAgent {
    fn id(&self) -> AgentId { AgentId::Export }
    fn state(&self) -> AgentState { self.state.clone() }
    async fn initialize(&mut self) -> Result<()> { self.state = AgentState::Idle; Ok(()) }
    async fn execute(&self, action: &str, params: serde_json::Value, ctx: &AgentContext) -> Result<serde_json::Value> {
        let doc = ctx.document.as_ref().ok_or_else(|| SeeHtmlError::InvalidDocument("No document".into()))?;
        let result = match action {
            "export_pptx" => {
                let theme = params.get("theme").and_then(|v| serde_json::from_value(v.clone()).ok()).unwrap_or_default();
                let output_path = params.get("output_path").and_then(|v| v.as_str()).map(std::path::PathBuf::from)
                    .unwrap_or_else(|| std::path::PathBuf::from(format!("./output/{}.pptx", doc.title)));
                if let Some(parent) = output_path.parent() {
                    tokio::fs::create_dir_all(parent).await?;
                }
                let pptx = seehtml_export::build_pptx(doc, &theme)?;
                tokio::fs::write(&output_path, pptx).await?;
                output_path.to_string_lossy().to_string()
            }
            "export_markdown" => {
                let out = params.get("output_path").and_then(|v| v.as_str()).map(std::path::PathBuf::from);
                let opts = ExportOptions { format: ExportFormat::Markdown, output_path: out, theme: None, quality: None, include_assets: true, custom_styles: false };
                Self::export_markdown(doc, &opts).await?
            }
            "export_png" => {
                serde_json::json!({
                    "status": "ready",
                    "message": "Use the Preview tab to capture slides as PNG, then Save PNG",
                    "format": "png"
                }).to_string()
            }
            "export_html" => {
                let path = params.get("output_path").and_then(|v| v.as_str())
                    .unwrap_or("./output/document.html");
                let pb = std::path::PathBuf::from(path);
                if let Some(parent) = pb.parent() {
                    tokio::fs::create_dir_all(parent).await?;
                }
                tokio::fs::write(&pb, &doc.html_content).await?;
                pb.to_string_lossy().to_string()
            }
            _ => return Err(SeeHtmlError::AgentError { agent: "ExportAgent".into(), message: format!("Unknown: {}", action) }),
        };
        Ok(serde_json::json!({"output_path": result}))
    }
    fn capabilities(&self) -> Vec<AgentCapability> {
        vec![
            AgentCapability { action: "export_pptx".into(), description: "Export document as PowerPoint (PPTX) file".into(),
                parameters: vec![
                    CapabilityParameter { name: "theme".into(), param_type: "object".into(), description: "Theme config".into(), required: false },
                    CapabilityParameter { name: "output_path".into(), param_type: "string".into(), description: "Output file path".into(), required: false },
                ]},
            AgentCapability { action: "export_markdown".into(), description: "Export document as Markdown file".into(),
                parameters: vec![CapabilityParameter { name: "output_path".into(), param_type: "string".into(), description: "Output file path".into(), required: false }]},
            AgentCapability { action: "export_png".into(), description: "Export slides as PNG images (use Preview tab Capture)".into(),
                parameters: vec![]},
            AgentCapability { action: "export_html".into(), description: "Save document as HTML file".into(),
                parameters: vec![CapabilityParameter { name: "output_path".into(), param_type: "string".into(), description: "Output file path".into(), required: false }]},
        ]
    }
}